# permissions for end users to view queuesplits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: queue-split-operator
    app.kubernetes.io/managed-by: kustomize
  name: queuesplit-viewer-role
rules:
- apiGroups:
  - messaging.yok.travel
  resources:
  - queuesplits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messaging.yok.travel
  resources:
  - queuesplits/status
  verbs:
  - get
