---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - messaging.yok.travel
  resources:
  - queuesplits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messaging.yok.travel
  resources:
  - queuesplits/finalizers
  verbs:
  - update
- apiGroups:
  - messaging.yok.travel
  resources:
  - queuesplits/status
  verbs:
  - get
  - patch
  - update
