apiVersion: messaging.yok.travel/v1alpha1
kind: QueueSplit
metadata:
  name: test-queuesplit
  namespace: default
spec:
  replicas: 1
  secretName: queue-split-secret
  queueName: test-queue
  prefetchCount: 10
  destinations:
    - name: consumer-a
      weight: 50
    - name: consumer-b
      weight: 50
