apiVersion: messaging.yok.travel/v1alpha1
kind: QueueSplit
metadata:
  name: queuesplit-webhook-order
  namespace: default
spec:
  replicas: 2
  secretName: queue-split-secret
  queueName: test-queue
  prefetchCount: 10
  destinations:
    - name: consumer-a
      weight: 80
    - name: consumer-b
      weight: 20
